# Generated by Django 2.0 on 2020-02-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_massage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('photo', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=50)),
                ('cz', models.CharField(max_length=3)),
                ('region', models.CharField(max_length=30)),
            ],
        ),
    ]
